<?php
/**
 * Created by PhpStorm.
 * User: cashify
 * Date: 11/12/17
 * Time: 7:24 PM
 */

namespace common\models\cache;

use common\models\Transactions;

class TransactionsCache extends Transactions {

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }


}