<?php

namespace common\models;

use common\components\Utils;
use common\models\reglobe\TransactionsFilter;
use Yii;

/**
 * This is the model class for table "transactions".
 *
 * @property integer $id
 * @property integer $customer_id
 * @property integer $amount
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property string $cron_status
 *
 * @property User $customer
 */
class Transactions extends \yii\db\ActiveRecord
{
    const CRON_STATUS_SUM = 1;
    const CRON_STATUS_DEFAULT = 0;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'transactions';
    }

    public function beforeSave($insert)
    {
        $now = Utils::getNow();
        if($this->isNewRecord){
            $this->created_at = $now;
        }
        $this->updated_at = $now;

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public static function find(){
        return new TransactionsFilter(get_called_class());
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['customer_id', 'amount'], 'required'],
            [['customer_id', 'amount'], 'integer'],
            [['created_at', 'updated_at', 'deleted_at','cron_status'], 'safe'],
            [['customer_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['customer_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'customer_id' => 'Customer ID',
            'amount' => 'Amount',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
            'cron_status' => 'Cron Status',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCustomer()
    {
        return $this->hasOne(User::className(), ['id' => 'customer_id']);
    }
}
